### ISSUE TITLE
[BUG] Is ItemsAdder Item  Condition can't use is not

### ISSUE THREAD

**Issue by killertuling** [Asleeepp/skript-itemsadder#10]
**Describe the bug**

**To Reproduce**
It will work：
![image](https://github.com/Asleeepp/skript-itemsadder/assets/19590076/9433a931-e5f5-4bc3-b022-2efedc46b7c5)

but It produces errors
![image](https://github.com/Asleeepp/skript-itemsadder/assets/19590076/1f2b7d9a-41ff-43da-8e0c-fd6fb409b377)
![image](https://github.com/Asleeepp/skript-itemsadder/assets/19590076/4c9d928d-fb3d-48ec-a49e-8ca7fdf01ac5)

**Expected behavior**

**Screenshots**

**Server Version (/version):**
 - 1.20.4

**Skript and skript-itemadder version:**
 - Skript: 2.8.4
 - skript-itemsadder: 1.4.1
 

**Additional context**

**Comment by Asleeepp** [comment]
Will be fixed in the next update 👍
