### ISSUE TITLE
[BUG] event-items not working in plural

### ISSUE THREAD

**Issue by DRAGNIL68** [Asleeepp/skript-itemsadder#11]
**Describe the bug**
when i try and check if a player right clicks on more than 1 custom item it just refuses to work
`on right click:
    if event-item is customitem "namespace:item":
        send "test" to player`

**To Reproduce**
1. copy the code above
2. try and right click on more than 1 custom item

**Expected behavior**
if i have more than 1 of a custom item in one slot in my inventory it will not register it but if a only have 1 it works fine

**Server Version (/version):**
 - papermc 1.20.2 latest build

**Skript and skript-itemadder version:**
 - Skript: 2.8.2
 - skript-itemsadder: 1.5
 

**Additional context**
I'm not really sure if this is your plugin or IA if it is IA i apologize for wasting your time.

**Comment by DRAGNIL68** [comment]
i have no clue why the code didn't format correctly
![image](https://github.com/Asleeepp/skript-itemsadder/assets/145930809/10b62194-4e34-4752-a43f-99bf0b32020d)

**Comment by Asleeepp** [comment]
> i have no clue why the code didn't format correctly
> 
> ![image](https://github.com/Asleeepp/skript-itemsadder/assets/145930809/10b62194-4e34-4752-a43f-99bf0b32020d)
> 
> 

Ok so, number one you are using the syntax wrong, and number two you arent even using namespace:id in this screenshot, can you correct it, and tell me if you still encounter this issue.

**Comment by DRAGNIL68** [comment]
yep sorry for that i did test it with a namespace its just i was testing

**Comment by Asleeepp** [comment]
You are still using the wrong syntax

**Comment by DRAGNIL68** [comment]
![image](https://github.com/Asleeepp/skript-itemsadder/assets/145930809/e9d661e7-1ccd-46d2-999b-e8eafaa0a9a1)
this is what i meant i have basically never submitted a bug report so I'm not verry good at it

**Comment by Asleeepp** [comment]
> ![image](https://private-user-images.githubusercontent.com/145930809/322213112-e9d661e7-1ccd-46d2-999b-e8eafaa0a9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMjc5MjcsIm5iZiI6MTcxMzAyNzYyNywicGF0aCI6Ii8xNDU5MzA4MDkvMzIyMjEzMTEyLWU5ZDY2MWU3LTFjY2QtNDZkMi05OTliLWU4ZWFmYWEwYTlhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxNzAwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTEyZWJhNmZhNmZkYWNhMTdmYmVhMjNkN2NmNjFjN2QyODQyYWNiNmZlNjViN2Y3NjhmZmIzZmY3ODczYjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zSlmG2r3qVHqPE18MyLgXmdQ91eIIaj0OuFlX4WrxvA) this is what i meant i have basically never submitted a bug report so I'm not verry good at it. i am 99% sure that is correct yes?

brother, please read the docs before sending a new comment. 

https://skripthub.net/docs/?id=11302

**Comment by DRAGNIL68** [comment]
i could have sworn that 1-2 months ago it stated customitem. I am verry sorry for wasting your time
