### ISSUE TITLE
[FEATURE REQUEST] please make `(set|place) (custom|ia|itemsadder) crop[s] %string% at %location%` effect

### ISSUE THREAD

**Issue by bgchoi1118** [Asleeepp/skript-itemsadder#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
that effect is place customcrops crop at pot.

**Describe alternatives you've considered**
I use https://skripthub.net/docs/?id=11287 this effect but in case of customcrops with https://skripthub.net/docs/?id=11272 this event, that doesn't work.

**Additional context**

**Comment by Asleeepp** [comment]
Will be in the next update 👍

**Comment by bgchoi1118** [comment]
May I know when there will be an update?

**Comment by Asleeepp** [comment]
> May I know when there will be an update?

Most likely next week if i have time :)

**Comment by Asleeepp** [comment]
> > May I know when there will be an update?
> 
> Most likely next week if i have time :)

whoops, i've been slacking lately, promise to get it out soon though 🙏
