### ISSUE TITLE
[FEATURE REQUEST] please make `get id of block/item` expression

### ISSUE THREAD

**Issue by bgchoi1118** [Asleeepp/skript-itemsadder#14]
**Is your feature request related to a problem? Please describe.**
I want to get id of block/item but i can only use nbt tag. But it is so difficult.
**Describe the solution you'd like**
When i use expression `get id of player's tool`, it returns `namespace:id` like `customcrops:grape`

**Describe alternatives you've considered**

**Additional context**

**Comment by Asleeepp** [comment]
Will be in the next update 👍
