### ISSUE TITLE
Replacing furniture that is more than 1x1x1 size results in buggy behaviour.

### ISSUE THREAD

**Issue by MaliWhiteTea** [Asleeepp/skript-itemsadder#4]
hi,

how can i use the "replace ia furniture" effect? what should i use for location? 
i want to change the furniture at the same location
![image](https://github.com/Asleeepp/skript-itemsadder/assets/118561035/cbcfb100-e576-4178-9e0e-4052e787d9c3)

and dou you have a discord account?

**Comment by MaliWhiteTea** [comment]
i tried this:
![image](https://github.com/Asleeepp/skript-itemsadder/assets/118561035/af98edf7-29a9-4cac-999f-4fc0f32664dd)
it was weird if you try to replace a furniture bigger than 1x1x1 hitbox like this:
![image](https://github.com/Asleeepp/skript-itemsadder/assets/118561035/27b712e9-4860-4162-bc19-84e38c84a4dd)

**Comment by Asleeepp** [comment]
> hi,
> 
> how can i use the "replace ia furniture" effect? what should i use for location? i want to change the furniture at the same location

The location should be at where the invisible armor stand is (iirc). I didn't make this effect, someone opened a pull request and requested to add it. In their video. It seemed like the effect worked fine for them.

> and dou you have a discord account?

Yes, my username on discord is Asleepp

**Comment by Fusezion** [comment]
Sorry if this seems weird, but from what I understand from the `CustomFurniture#replaceFurniture` method it's not intended to be treated like "replace existing furniture" it's meant to be used to replace/change an existing furniture to another furniture the fact the rotation isn't the same makes sense as you likely aren't using the same yaw/pitch the previous furniture was using.

**Comment by Fusezion** [comment]
So as I said it's directly controlled by yaw/pitch along side the click location, if he didn't originally click in either of those locations it makes sense as to why it's not placing in the same location. You personally have no method or way to change this behavior unless you can store the origin location onto the armor stand and update the placement from there.

While there is a method like `CustomFurnature#getArmorStand()` and `CustomFurnature#getEntity()` I can't if any of them represent the origin location
