### ISSUE TITLE
some possible bugs

### ISSUE THREAD

**Issue by DRAGNIL68** [Asleeepp/skript-itemsadder#5]
hi i was using your plugin on minecraft papermc 1.20.2 not sure if this is a bug but the 2 code snippets i put in don't seem to work. Also this is my first time submitting something to a github repo
`set usages of itemsadder item "misc:jump_boost" to 0`
`set item cooldown of  itemsadder item "misc:jump_boost" for player to 1 minute`

**Comment by DRAGNIL68** [comment]
also my IA config `  jump_boost:
    display_name: Jump Boost
    permission: user.tool.powerup
    lore:
      - lets you jump
    durability:
      unbreakable: true
      usages: 1
    resource:
      material: IRON_HORSE_ARMOR
      generate: true
      textures:
      - jump_orb
    item_flags:
    - HIDE_ATTRIBUTES
    - HIDE_DESTROYS
    - HIDE_ENCHANTS
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
    - HIDE_UNBREAKABLE
    events:
      interact:
        right:
          play_sound:
            name: minecraft:block.glass.break
            volume: 2
            pitch: 2
          decrement_usages:
            amount: 1`

**Comment by DRAGNIL68** [comment]
also why do you allow people to just use the item id instead if the full namespace:id?

**Comment by Asleeepp** [comment]
> hi i was using your plugin on minecraft papermc 1.20.2 not sure if this is a bug but the 2 code snippets i put in don't seem to work. Also this is my first time submitting something to a github repo `set usages of itemsadder item "misc:jump_boost" to 0` `set item cooldown of itemsadder item "misc:jump_boost" for player to 1 minute`

Some skript syntaxes might not work with the expressions from skript-itemsadder, as itemsadder can be quite finicky sometimes, and the developer used alot of hacky methods to achieve this stuff. Theres not much I can do about this. For why the usages isn't working, I'll look into it.

**Comment by Asleeepp** [comment]
> also why do you allow people to just use the item id instead if the full namespace:id?

I don't think I can force this, if i could, then i might add it. But I think users will figure out that you will need to use namespace:id, as its already used everywhere in itemsadder anyway.
